// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files

use crate::ffi;
use glib::translate::*;

/// May block for a Wayland roundtrip the first time it's called.
///
/// # Returns
///
/// [`true`] if the platform is Wayland and Wayland compositor supports the
/// Session Lock protocol.
#[doc(alias = "gtk_session_lock_is_supported")]
pub fn is_supported() -> bool {
    assert_initialized_main_thread!();
    unsafe { from_glib(ffi::gtk_session_lock_is_supported()) }
}
