version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Cargo workspace
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      gtk4:
        update-types:
          - "major"
          - "minor"
        patterns:
          - "glib"
          - "glib-sys"
          - "gdk4"
          - "gdk4-sys"
          - "gtk4-sys"
          - "gtk4"
          - "gio"

  # Standalone example crate
  - package-ecosystem: "cargo"
    directory: "/gtk4-layer-shell/examples/relm4"
    schedule:
      interval: "daily"