// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_EDGE_BOTTOM);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_EDGE_ENTRY_NUMBER);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_EDGE_LEFT);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_EDGE_RIGHT);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_EDGE_TOP);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_KEYBOARD_MODE_ENTRY_NUMBER);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_KEYBOARD_MODE_EXCLUSIVE);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_KEYBOARD_MODE_NONE);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_KEYBOARD_MODE_ON_DEMAND);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_LAYER_BACKGROUND);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_LAYER_BOTTOM);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_LAYER_ENTRY_NUMBER);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_LAYER_OVERLAY);
    PRINT_CONSTANT((gint) GTK_LAYER_SHELL_LAYER_TOP);
    return 0;
}
