// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GtkLayerShellEdge", sizeof(GtkLayerShellEdge), alignof(GtkLayerShellEdge));
    printf("%s;%zu;%zu\n", "GtkLayerShellKeyboardMode", sizeof(GtkLayerShellKeyboardMode), alignof(GtkLayerShellKeyboardMode));
    printf("%s;%zu;%zu\n", "GtkLayerShellLayer", sizeof(GtkLayerShellLayer), alignof(GtkLayerShellLayer));
    return 0;
}
