name: "Build x86"

permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "true"
      - uses: ./.github/actions/install_deps
      - uses: ./.github/actions/install_msrv_toolchain
      - name: Install gir
        working-directory: ./gir
        run: cargo install --force --path .
      - uses: ./.github/actions/build_regenerate_test
        with:
          fail_on_dirty: "true"
